=== storytron/face-editor/res/expressionSet.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="expressionSet">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="expression" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="feature" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="point" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:byte" name="leftLineThickness" use="optional"/>
                            <xs:attribute type="xs:short" name="leftX" use="optional"/>
                            <xs:attribute type="xs:short" name="leftY" use="optional"/>
                            <xs:attribute type="xs:byte" name="rightLineThickness" use="optional"/>
                            <xs:attribute type="xs:short" name="rightX" use="optional"/>
                            <xs:attribute type="xs:short" name="rightY" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="name" use="optional"/>
                  <xs:attribute type="xs:float" name="participation" use="optional"/>
                  <xs:attribute type="xs:byte" name="size" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="aLabel" use="optional"/>
            <xs:attribute type="xs:byte" name="attack" use="optional"/>
            <xs:attribute type="xs:byte" name="bSustain" use="optional"/>
            <xs:attribute type="xs:byte" name="decay" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== storytron/face-editor/res/expressions copy.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<expressionSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="expressionSet.xsd">
<expression aLabel="no emotion  " attack="0" bSustain="0" decay="0">
<feature name="Eye" participation="1.0" size="8">
<point leftLineThickness="3" leftX="56" leftY="240" rightLineThickness="3" rightX="56" rightY="240"/>
<point leftLineThickness="3" leftX="88" leftY="204" rightLineThickness="3" rightX="88" rightY="204"/>
<point leftLineThickness="3" leftX="152" leftY="184" rightLineThickness="3" rightX="152" rightY="184"/>
<point leftLineThickness="3" leftX="220" leftY="204" rightLineThickness="3" rightX="220" rightY="204"/>
<point leftLineThickness="3" leftX="256" leftY="240" rightLineThickness="3" rightX="256" rightY="240"/>
<point leftLineThickness="3" leftX="216" leftY="248" rightLineThickness="3" rightX="216" rightY="248"/>
<point leftLineThickness="3" leftX="152" leftY="256" rightLineThickness="3" rightX="152" rightY="256"/>
<point leftLineThickness="3" leftX="96" leftY="248" rightLineThickness="3" rightX="96" rightY="248"/>
</feature>
<feature name="Iris" participation="1.0" size="1">
<point leftLineThickness="3" leftX="148" leftY="220" rightLineThickness="3" rightX="148" rightY="220"/>
</feature>
<feature name="Orb Line" participation="1.0" size="4">
<point leftLineThickness="3" leftX="88" leftY="284" rightLineThickness="3" rightX="88" rightY="284"/>
<point leftLineThickness="3" leftX="132" leftY="312" rightLineThickness="3" rightX="132" rightY="312"/>
<point leftLineThickness="3" leftX="176" leftY="312" rightLineThickness="3" rightX="176" rightY="312"/>
<point leftLineThickness="3" leftX="236" leftY="284" rightLineThickness="3" rightX="236" rightY="284"/>
</feature>
<feature name="Brow Line" participation="1.0" size="3">
<point leftLineThickness="3" leftX="16" leftY="232" rightLineThickness="3" rightX="16" rightY="232"/>
<point leftLineThickness="3" leftX="20" leftY="176" rightLineThickness="3" rightX="20" rightY="176"/>
<point leftLineThickness="3" leftX="32" leftY="132" rightLineThickness="3" rightX="32" rightY="132"/>
</feature>
<feature name="Eyebrow" participation="1.0" size="5">
<point leftLineThickness="3" leftX="48" leftY="128" rightLineThickness="3" rightX="48" rightY="128"/>
<point leftLineThickness="3" leftX="100" leftY="96" rightLineThickness="3" rightX="100" rightY="96"/>
<point leftLineThickness="3" leftX="168" leftY="88" rightLineThickness="3" rightX="168" rightY="88"/>
<point leftLineThickness="3" leftX="236" leftY="116" rightLineThickness="3" rightX="236" rightY="116"/>
<point leftLineThickness="3" leftX="304" leftY="172" rightLineThickness="3" rightX="304" rightY="172"/>
</feature>
<feature name="Nose" participation="1.0" size="1">
<point leftLineThickness="3" leftX="0" leftY="256" rightLineThickness="3" rightX="0" rightY="256"/>
</feature>
<feature name="Jowl" participation="1.0" size="4">
<point leftLineThickness="3" leftX="88" leftY="456" rightLineThickness="3" rightX="88" rightY="452"/>
<point leftLineThickness="3" leftX="136" leftY="486" rightLineThickness="3" rightX="136" rightY="486"/>
<point leftLineThickness="3" leftX="176" leftY="512" rightLineThickness="3" rightX="176" rightY="512"/>
<point leftLineThickness="3" leftX="212" leftY="568" rightLineThickness="3" rightX="212" rightY="580"/>
</feature>
<feature name="UpperLip" participation="1.0" size="5">
<point leftLineThickness="3" leftX="18" leftY="571" rightLineThickness="3" rightX="18" rightY="571"/>
<point leftLineThickness="3" leftX="73" leftY="587" rightLineThickness="3" rightX="73" rightY="587"/>
<point leftLineThickness="3" leftX="134" leftY="612" rightLineThickness="3" rightX="134" rightY="612"/>
<point leftLineThickness="3" leftX="84" leftY="625" rightLineThickness="3" rightX="84" rightY="625"/>
<point leftLineThickness="3" leftX="17" leftY="609" rightLineThickness="3" rightX="17" rightY="609"/>
</feature>
<feature name="LowerLip" participation="1.0" size="4">
<point leftLineThickness="3" leftX="9" leftY="636" rightLineThickness="3" rightX="9" rightY="636"/>
<point leftLineThickness="3" leftX="92" leftY="664" rightLineThickness="3" rightX="92" rightY="664"/>
<point leftLineThickness="3" leftX="47" leftY="672" rightLineThickness="3" rightX="47" rightY="672"/>
<point leftLineThickness="3" leftX="14" leftY="669" rightLineThickness="3" rightX="14" rightY="669"/>
</feature>
</expression>
<expression aLabel="no excursion" attack="1" bSustain="0" decay="0">
<feature name="Eye" participation="1.0" size="8">
<point leftLineThickness="3" leftX="56" leftY="240" rightLineThickness="3" rightX="56" rightY="240"/>
<point leftLineThickness="3" leftX="88" leftY="204" rightLineThickness="3" rightX="88" rightY="204"/>
<point leftLineThickness="3" leftX="152" leftY="184" rightLineThickness="3" rightX="152" rightY="184"/>
<point leftLineThickness="3" leftX="220" leftY="204" rightLineThickness="3" rightX="220" rightY="204"/>
<point leftLineThickness="3" leftX="256" leftY="240" rightLineThickness="3" rightX="256" rightY="240"/>
<point leftLineThickness="3" leftX="216" leftY="248" rightLineThickness="3" rightX="216" rightY="248"/>
<point leftLineThickness="3" leftX="152" leftY="256" rightLineThickness="3" rightX="152" rightY="256"/>
<point leftLineThickness="3" leftX="96" leftY="248" rightLineThickness="3" rightX="96" rightY="248"/>
</feature>
<feature name="Iris" participation="1.0" size="1">
<point leftLineThickness="3" leftX="148" leftY="220" rightLineThickness="3" rightX="148" rightY="220"/>
</feature>
<feature name="Orb Line" participation="1.0" size="4">
<point leftLineThickness="3" leftX="88" leftY="284" rightLineThickness="3" rightX="88" rightY="284"/>
<point leftLineThickness="3" leftX="132" leftY="312" rightLineThickness="3" rightX="132" rightY="312"/>
<point leftLineThickness="3" leftX="176" leftY="312" rightLineThickness="3" rightX="176" rightY="312"/>
<point leftLineThickness="3" leftX="236" leftY="284" rightLineThickness="3" rightX="236" rightY="284"/>
</feature>
<feature name="Brow Line" participation="1.0" size="3">
<point leftLineThickness="3" leftX="16" leftY="232" rightLineThickness="3" rightX="16" rightY="232"/>
<point leftLineThickness="3" leftX="20" leftY="176" rightLineThickness="3" rightX="20" rightY="176"/>
<point leftLineThickness="3" leftX="32" leftY="132" rightLineThickness="3" rightX="32" rightY="132"/>
</feature>
<feature name="Eyebrow" participation="1.0" size="5">
<point leftLineThickness="3" leftX="48" leftY="128" rightLineThickness="3" rightX="48" rightY="128"/>
<point leftLineThickness="3" leftX="100" leftY="96" rightLineThickness="3" rightX="100" rightY="96"/>
<point leftLineThickness="3" leftX="168" leftY="88" rightLineThickness="3" rightX="168" rightY="88"/>
<point leftLineThickness="3" leftX="236" leftY="116" rightLineThickness="3" rightX="236" rightY="116"/>
<point leftLineThickness="3" leftX="304" leftY="172" rightLineThickness="3" rightX="304" rightY="172"/>
</feature>
<feature name="Nose" participation="1.0" size="1">
<point leftLineThickness="3" leftX="0" leftY="256" rightLineThickness="3" rightX="0" rightY="256"/>
</feature>
<feature name="Jowl" participation="1.0" size="4">
<point leftLineThickness="3" leftX="88" leftY="456" rightLineThickness="3" rightX="88" rightY="452"/>
<point leftLineThickness="3" leftX="136" leftY="486" rightLineThickness="3" rightX="136" rightY="486"/>
<point leftLineThickness="3" leftX="176" leftY="512" rightLineThickness="3" rightX="176" rightY="512"/>
<point leftLineThickness="3" leftX="212" leftY="568" rightLineThickness="3" rightX="212" rightY="580"/>
</feature>
<feature name="UpperLip" participation="1.0" size="5">
<point leftLineThickness="3" leftX="18" leftY="571" rightLineThickness="3" rightX="18" rightY="571"/>
<point leftLineThickness="3" leftX="73" leftY="587" rightLineThickness="3" rightX="73" rightY="587"/>
<point leftLineThickness="3" leftX="134" leftY="612" rightLineThickness="3" rightX="134" rightY="612"/>
<point leftLineThickness="3" leftX="84" leftY="625" rightLineThickness="3" rightX="84" rightY="625"/>
<point leftLineThickness="3" leftX="17" leftY="609" rightLineThickness="3" rightX="17" rightY="609"/>
</feature>
<feature name="LowerLip" participation="1.0" size="4">
<point leftLineThickness="3" leftX="9" leftY="636" rightLineThickness="3" rightX="9" rightY="636"/>
<point leftLineThickness="3" leftX="92" leftY="664" rightLineThickness="3" rightX="92" rightY="664"/>
<point leftLineThickness="3" leftX="47" leftY="672" rightLineThickness="3" rightX="47" rightY="672"/>
<point leftLineThickness="3" leftX="14" leftY="669" rightLineThickness="3" rightX="14" rightY="669"/>
</feature>
</expression>
<expression aLabel="null        " attack="0" bSustain="0" decay="0">
<feature name="Eye" participation="1.0" size="8">
<point leftLineThickness="3" leftX="56" leftY="240" rightLineThickness="3" rightX="56" rightY="240"/>
<point leftLineThickness="3" leftX="88" leftY="204" rightLineThickness="3" rightX="88" rightY="204"/>
<point leftLineThickness="3" leftX="152" leftY="184" rightLineThickness="3" rightX="152" rightY="184"/>
<point leftLineThickness="3" leftX="220" leftY="204" rightLineThickness="3" rightX="220" rightY="204"/>
<point leftLineThickness="3" leftX="256" leftY="240" rightLineThickness="3" rightX="256" rightY="240"/>
<point leftLineThickness="3" leftX="216" leftY="248" rightLineThickness="3" rightX="216" rightY="248"/>
<point leftLineThickness="3" leftX="152" leftY="256" rightLineThickness="3" rightX="152" rightY="256"/>
<point leftLineThickness="3" leftX="96" leftY="248" rightLineThickness="3" rightX="96" rightY="248"/>
</feature>
<feature name="Iris" participation="1.0" size="1">
<point leftLineThickness="3" leftX="148" leftY="220" rightLineThickness="3" rightX="148" rightY="220"/>
</feature>
<feature name="Orb Line" participation="1.0" size="4">
